# Issue and PR labels for rocm-nightly-flake.
# Sync with: gh label import .github/labels.yml

- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: enhancement
  color: "a2eeef"
  description: New feature or request

- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation

- name: dependencies
  color: "0366d6"
  description: Dependency updates

- name: automated
  color: "ededed"
  description: Created by automation

- name: ci
  color: "fbca04"
  description: CI/CD changes

- name: gpu-detection
  color: "e99695"
  description: GPU detection or driver issues

- name: nixos-module
  color: "bfd4f2"
  description: NixOS module related

- name: packaging
  color: "c5def5"
  description: Nix packaging and derivation

- name: upstream
  color: "f9d0c4"
  description: Issue with upstream ROCm tarball
